name: Push Lambda fn docker image to ECR

on:  
  push:
    tags:
      - 'v*'

permissions:
  id-token: write
  contents: read
  deployments: write

env:
  ECR_REPOSITORY: serverless-security-system-process-s3-videos-lambda-fn
  REGION: us-east-1

jobs:
  deploy:
    name: Build & Deploy image
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Get the version
        id: get_image_tag
        run: echo ::set-output name=DOCKER_IMAGE::${GITHUB_REF/refs\/tags\//}


      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.IAM_ROLE_ARN }}
          aws-region: ${{ env.REGION }}


      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1


      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ steps.get_image_tag.outputs.DOCKER_IMAGE }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

          docker tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:latest 
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
